/**
 * Typed API contract, derived from the backend OpenAPI schema.
 *
 * Single source of truth: ../../openapi.json (generated by FastAPI).
 * Regenerate the schema after backend changes with:  npm run gen:api
 *
 * Do NOT hand-edit ./api-schema.ts — it is generated. Import domain types
 * from here so the frontend can never silently drift from the backend.
 */
import type { components } from "./api-schema";

export type Schemas = components["schemas"];

// ── Domain entities (API response shapes) ────────────────────────────────
export type Attraction = Schemas["AttractionResponse"];
export type Hotel = Schemas["HotelResponse"];
export type Restaurant = Schemas["RestaurantResponse"];
export type Event = Schemas["EventResponse"];
export type Itinerary = Schemas["ItineraryResponse"];
export type User = Schemas["UserResponse"];
export type Conversation = Schemas["ConversationResponse"];
export type Weather = Schemas["WeatherResponse"];
export type Recommendation = Schemas["RecommendationResponse"];
export type Transport = Schemas["TransportResponse"];
export type Feedback = Schemas["FeedbackResponse"];
export type SafetyScore = Schemas["SafetyScoreResponse"];
