"""
Google Calendar Export Service
Exports itineraries to Google Calendar
"""

import logging
from datetime import datetime, timedelta
from typing import Optional, Dict, Any

try:
    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build
    from googleapiclient.errors import HttpError
    GOOGLE_API_AVAILABLE = True
except ImportError:
    GOOGLE_API_AVAILABLE = False
    logging.warning("Google API client not installed. Calendar export will not work.")

from backend.app.models.itinerary import TripItinerary
from backend.app.core.config import settings

logger = logging.getLogger(__name__)


class CalendarExportService:
    """Service for exporting itineraries to Google Calendar"""
    
    def __init__(self):
        self.service = None
    
    async def export_to_google_calendar(
        self,
        itinerary: TripItinerary,
        user_credentials: Dict[str, str]
    ) -> Dict[str, Any]:
        """
        Export itinerary to Google Calendar
        
        Args:
            itinerary: TripItinerary object
            user_credentials: User's Google OAuth credentials
                {
                    "token": "access_token",
                    "refresh_token": "refresh_token",
                    "token_uri": "https://oauth2.googleapis.com/token",
                    "client_id": "...",
                    "client_secret": "...",
                    "scopes": ["https://www.googleapis.com/auth/calendar"]
                }
        
        Returns:
            Dict with calendar_id and event_ids
        """
        if not GOOGLE_API_AVAILABLE:
            raise ImportError(
                "Google API client not installed. "
                "Install with: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client"
            )
        
        try:
            # Create credentials from user's OAuth token
            creds = Credentials(
                token=user_credentials.get("token"),
                refresh_token=user_credentials.get("refresh_token"),
                token_uri="https://oauth2.googleapis.com/token",
                client_id=settings.GOOGLE_OAUTH_CLIENT_ID,
                client_secret=settings.GOOGLE_OAUTH_CLIENT_SECRET,
                scopes=["https://www.googleapis.com/auth/calendar"]
            )
            
            # Build Google Calendar service
            service = build('calendar', 'v3', credentials=creds)
            
            # Create calendar for this trip
            calendar_name = f"{itinerary.title} - Sri Lanka Tour"
            calendar = {
                'summary': calendar_name,
                'description': f"Trip to {itinerary.destination} for {itinerary.duration_days} days. "
                              f"Generated by Sri Lanka Tourism Chatbot.",
                'timeZone': 'Asia/Colombo'
            }
            
            created_calendar = service.calendars().insert(body=calendar).execute()
            calendar_id = created_calendar['id']
            
            logger.info(f"Created Google Calendar: {calendar_id}")
            
            # Add events for each activity
            event_ids = []
            
            for day in itinerary.days:
                for activity in day.activities:
                    event = self._create_calendar_event(
                        itinerary,
                        day,
                        activity
                    )
                    
                    created_event = service.events().insert(
                        calendarId=calendar_id,
                        body=event
                    ).execute()
                    
                    event_ids.append(created_event['id'])
            
            logger.info(f"Added {len(event_ids)} events to Google Calendar")
            
            # Get calendar link
            calendar_url = f"https://calendar.google.com/calendar/u/0?cid={calendar_id}"
            
            return {
                "success": True,
                "calendar_id": calendar_id,
                "calendar_url": calendar_url,
                "events_created": len(event_ids),
                "event_ids": event_ids
            }
            
        except HttpError as e:
            logger.error(f"Google Calendar API error: {e}")
            raise Exception(f"Failed to export to Google Calendar: {e}")
        except Exception as e:
            logger.error(f"Calendar export error: {e}", exc_info=True)
            raise
    
    def _create_calendar_event(
        self,
        itinerary: TripItinerary,
        day,
        activity
    ) -> Dict[str, Any]:
        """Create a Google Calendar event from activity"""
        
        # Parse time slot (e.g., "09:00 AM - 11:00 AM")
        start_time, end_time = self._parse_time_slot(activity.time_slot)
        
        # Create datetime objects
        start_datetime = datetime.combine(day.date, start_time)
        
        if end_time:
            end_datetime = datetime.combine(day.date, end_time)
        else:
            # Default duration: 2 hours
            end_datetime = start_datetime + timedelta(hours=2)
        
        # Build event description
        description_parts = []
        
        if activity.description:
            description_parts.append(activity.description)
        
        if activity.estimated_cost > 0:
            description_parts.append(f"\n💰 Estimated Cost: ${activity.estimated_cost:.2f}")
        
        if activity.rating:
            description_parts.append(f"\n⭐ Rating: {activity.rating}/5")
        
        if activity.booking_url:
            description_parts.append(f"\n\n🔗 Book here: {activity.booking_url}")
        
        if activity.tips:
            description_parts.append("\n\n💡 Tips:")
            for tip in activity.tips:
                description_parts.append(f"  • {tip}")
        
        description = "\n".join(description_parts)
        
        # Create event
        event = {
            'summary': f"{activity.title}",
            'location': activity.location or itinerary.destination,
            'description': description,
            'start': {
                'dateTime': start_datetime.isoformat(),
                'timeZone': 'Asia/Colombo',
            },
            'end': {
                'dateTime': end_datetime.isoformat(),
                'timeZone': 'Asia/Colombo',
            },
            'colorId': self._get_event_color(activity.activity_type),
            'reminders': {
                'useDefault': False,
                'overrides': [
                    {'method': 'popup', 'minutes': 30},
                    {'method': 'popup', 'minutes': 1440},  # 1 day before
                ],
            },
        }
        
        return event
    
    def _parse_time_slot(self, time_slot: str) -> tuple:
        """Parse time slot string into start and end times"""
        try:
            # Handle formats like "09:00 AM - 11:00 AM" or "Check-in: 02:00 PM"
            if '-' in time_slot:
                parts = time_slot.split('-')
                start_str = parts[0].strip()
                end_str = parts[1].strip() if len(parts) > 1 else None
            else:
                # Extract time from strings like "Check-in: 02:00 PM"
                if ':' in time_slot:
                    start_str = time_slot.split(':', 1)[1].strip()
                else:
                    start_str = time_slot.strip()
                end_str = None
            
            # Parse start time
            start_time = datetime.strptime(start_str, '%I:%M %p').time()
            
            # Parse end time
            if end_str:
                end_time = datetime.strptime(end_str, '%I:%M %p').time()
            else:
                end_time = None
            
            return start_time, end_time
            
        except Exception as e:
            logger.warning(f"Failed to parse time slot '{time_slot}': {e}")
            # Default to 9 AM
            return datetime.strptime('09:00 AM', '%I:%M %p').time(), None
    
    def _get_event_color(self, activity_type: str) -> str:
        """Get Google Calendar color ID for activity type"""
        color_map = {
            'attraction': '5',  # Yellow
            'hotel': '3',       # Purple
            'meal': '2',        # Green
            'transport': '1',   # Blue
            'activity': '7',    # Cyan
            'tour': '9',        # Blue
        }
        return color_map.get(activity_type, '5')
    
    async def generate_ics_file(
        self,
        itinerary: TripItinerary
    ) -> str:
        """
        Generate ICS (iCalendar) file for download
        
        Args:
            itinerary: TripItinerary object
        
        Returns:
            ICS file content as string
        """
        try:
            ics_lines = []
            
            # Header
            ics_lines.append("BEGIN:VCALENDAR")
            ics_lines.append("VERSION:2.0")
            ics_lines.append("PRODID:-//Sri Lanka Tourism Chatbot//EN")
            ics_lines.append(f"X-WR-CALNAME:{itinerary.title}")
            ics_lines.append("X-WR-TIMEZONE:Asia/Colombo")
            
            # Add events
            for day in itinerary.days:
                for activity in day.activities:
                    event_lines = self._create_ics_event(itinerary, day, activity)
                    ics_lines.extend(event_lines)
            
            # Footer
            ics_lines.append("END:VCALENDAR")
            
            ics_content = "\n".join(ics_lines)
            
            logger.info(f"Generated ICS file for itinerary {itinerary.id}")
            
            return ics_content
            
        except Exception as e:
            logger.error(f"Failed to generate ICS file: {e}", exc_info=True)
            raise
    
    def _create_ics_event(self, itinerary, day, activity) -> list:
        """Create ICS event lines"""
        lines = []
        
        # Parse time
        start_time, end_time = self._parse_time_slot(activity.time_slot)
        start_datetime = datetime.combine(day.date, start_time)
        
        if end_time:
            end_datetime = datetime.combine(day.date, end_time)
        else:
            end_datetime = start_datetime + timedelta(hours=2)
        
        # Format datetime for ICS (YYYYMMDDTHHMMSS)
        start_str = start_datetime.strftime("%Y%m%dT%H%M%S")
        end_str = end_datetime.strftime("%Y%m%dT%H%M%S")
        
        # Create unique ID
        event_id = f"{itinerary.id}-{day.day_number}-{activity.title[:20].replace(' ', '-')}"
        
        lines.append("BEGIN:VEVENT")
        lines.append(f"UID:{event_id}")
        lines.append(f"DTSTAMP:{datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')}")
        lines.append(f"DTSTART:{start_str}")
        lines.append(f"DTEND:{end_str}")
        lines.append(f"SUMMARY:{activity.title}")
        lines.append(f"LOCATION:{activity.location or itinerary.destination}")
        
        if activity.description:
            # Escape special characters
            desc = activity.description.replace('\n', '\\n').replace(',', '\\,')
            lines.append(f"DESCRIPTION:{desc}")
        
        lines.append("END:VEVENT")
        
        return lines


# Singleton instance
_calendar_service = None

def get_calendar_export_service() -> CalendarExportService:
    """Get calendar export service singleton"""
    global _calendar_service
    if _calendar_service is None:
        _calendar_service = CalendarExportService()
    return _calendar_service

