"""
Import Sample Tourism Data into MongoDB
========================================

Imports the sample data generated by generate_sample_data.py
"""

import asyncio
import json
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from backend.app.core.database import init_database, db
from backend.app.models.emergency import Emergency
from backend.app.models.hotel import Hotel
from backend.app.models.restaurant import Restaurant
from backend.app.models.event import Event


async def import_data():
    """Import sample data into MongoDB"""
    
    print("\n🔄 Importing Sample Tourism Data")
    print("=" * 60)
    
    # Initialize database
    try:
        await init_database()
        print("✅ Database connection established\n")
    except Exception as e:
        print(f"❌ Failed to connect to database: {e}")
        return
    
    # Load sample data
    data_file = project_root / "sample_tourism_data.json"
    
    if not data_file.exists():
        print(f"❌ Data file not found: {data_file}")
        print("💡 Run 'python scripts/generate_sample_data.py' first")
        return
    
    try:
        with open(data_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        print(f"✅ Loaded data from: {data_file}\n")
    except Exception as e:
        print(f"❌ Failed to load data: {e}")
        return
    
    stats = {
        "emergency": {"imported": 0, "skipped": 0, "errors": 0},
        "hotels": {"imported": 0, "skipped": 0, "errors": 0},
        "restaurants": {"imported": 0, "skipped": 0, "errors": 0},
        "events": {"imported": 0, "skipped": 0, "errors": 0}
    }
    
    # Import Emergency Services
    print("🚨 Importing Emergency Services...")
    for item in data.get("emergency_services", []):
        try:
            # Check if already exists
            existing = await Emergency.find_one(
                Emergency.phone == item.get("phone")
            )
            
            if existing:
                stats["emergency"]["skipped"] += 1
                continue
            
            # Create new emergency service
            emergency = Emergency(**item)
            await emergency.save()
            stats["emergency"]["imported"] += 1
            print(f"  ✅ {item['name']['en']}")
            
        except Exception as e:
            stats["emergency"]["errors"] += 1
            print(f"  ❌ Error: {e}")
    
    # Import Hotels
    print("\n🏨 Importing Hotels...")
    for item in data.get("hotels", []):
        try:
            # Check if already exists
            existing = await Hotel.find_one(
                Hotel.name.en == item["name"]["en"]
            )
            
            if existing:
                stats["hotels"]["skipped"] += 1
                continue
            
            # Create new hotel
            hotel = Hotel(**item)
            await hotel.save()
            stats["hotels"]["imported"] += 1
            print(f"  ✅ {item['name']['en']}")
            
        except Exception as e:
            stats["hotels"]["errors"] += 1
            print(f"  ❌ Error: {e}")
    
    # Import Restaurants
    print("\n🍽️  Importing Restaurants...")
    for item in data.get("restaurants", []):
        try:
            # Check if already exists
            existing = await Restaurant.find_one(
                Restaurant.name.en == item["name"]["en"]
            )
            
            if existing:
                stats["restaurants"]["skipped"] += 1
                continue
            
            # Create new restaurant
            restaurant = Restaurant(**item)
            await restaurant.save()
            stats["restaurants"]["imported"] += 1
            print(f"  ✅ {item['name']['en']}")
            
        except Exception as e:
            stats["restaurants"]["errors"] += 1
            print(f"  ❌ Error: {e}")
    
    # Import Events
    print("\n🎭 Importing Events...")
    for item in data.get("events", []):
        try:
            # Check if already exists
            existing = await Event.find_one(
                Event.title.en == item["title"]["en"]
            )
            
            if existing:
                stats["events"]["skipped"] += 1
                continue
            
            # Create new event
            event = Event(**item)
            await event.save()
            stats["events"]["imported"] += 1
            print(f"  ✅ {item['title']['en']}")
            
        except Exception as e:
            stats["events"]["errors"] += 1
            print(f"  ❌ Error: {e}")
    
    # Print summary
    print("\n" + "=" * 60)
    print("📊 Import Summary")
    print("=" * 60)
    
    total_imported = sum(s["imported"] for s in stats.values())
    total_skipped = sum(s["skipped"] for s in stats.values())
    total_errors = sum(s["errors"] for s in stats.values())
    
    print(f"\n🚨 Emergency Services:")
    print(f"   ✅ Imported: {stats['emergency']['imported']}")
    print(f"   ⏭️  Skipped:  {stats['emergency']['skipped']}")
    print(f"   ❌ Errors:   {stats['emergency']['errors']}")
    
    print(f"\n🏨 Hotels:")
    print(f"   ✅ Imported: {stats['hotels']['imported']}")
    print(f"   ⏭️  Skipped:  {stats['hotels']['skipped']}")
    print(f"   ❌ Errors:   {stats['hotels']['errors']}")
    
    print(f"\n🍽️  Restaurants:")
    print(f"   ✅ Imported: {stats['restaurants']['imported']}")
    print(f"   ⏭️  Skipped:  {stats['restaurants']['skipped']}")
    print(f"   ❌ Errors:   {stats['restaurants']['errors']}")
    
    print(f"\n🎭 Events:")
    print(f"   ✅ Imported: {stats['events']['imported']}")
    print(f"   ⏭️  Skipped:  {stats['events']['skipped']}")
    print(f"   ❌ Errors:   {stats['events']['errors']}")
    
    print("\n" + "=" * 60)
    print(f"📊 Total: {total_imported} imported, {total_skipped} skipped, {total_errors} errors")
    print("=" * 60)
    
    if total_imported > 0:
        print("\n✅ Data import completed successfully!")
        print("🚀 Run tests to verify: python -m pytest backend/tests/")
    else:
        print("\n⚠️  No new data imported (all records already exist)")


if __name__ == "__main__":
    asyncio.run(import_data())
